# permissions for end users to view addresspools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coilv2-addresspool-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - coil.cybozu.com
  resources:
  - addresspools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - addresspools/status
  verbs:
  - get
