# permissions for end users to view blockrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockrequest-viewer-role
rules:
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests/status
  verbs:
  - get
