# permissions for end users to view blockrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coilv2-blockrequest-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests/status
  verbs:
  - get
