# permissions for end users to edit blockrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockrequest-editor-role
rules:
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests/status
  verbs:
  - get
