# permissions for end users to edit egresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egress-editor-role
rules:
- apiGroups:
  - coil.cybozu.com
  resources:
  - egresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - egresses/status
  verbs:
  - get
