version: 2.1
commands:
  run-mtest:
    description: "multi-host test"
    parameters:
      runtime:
        type: string
      suite:
        type: string
      kubernetes-version:
        type: string
    steps:
      - run:
          name: Store Service Account
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT > account.json
            gcloud auth activate-service-account --key-file=account.json
      - run:
          command: |
            ./bin/run-mtest.sh <<parameters.runtime>> <<parameters.suite>> <<parameters.kubernetes-version>>
          no_output_timeout: 20m
      - run:
          name: Set the instance lifetime
          command: |
            . ./bin/env
            $GCLOUD compute instances add-metadata ${INSTANCE_NAME} --zone ${ZONE} \
              --metadata shutdown-at=$(date -Iseconds -d+30minutes)
          when: on_fail
      - run:
          name: Notify to Slack
          command: |
            . ./bin/env
            curl -X POST -H 'Content-type: application/json' --data "{
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"Failed: ${CIRCLE_USERNAME}'s workflow (${CIRCLE_JOB}) in <https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/workflows/${CIRCLE_PROJECT_REPONAME}|${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}> (<https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tree/${CIRCLE_BRANCH}|${CIRCLE_BRANCH}>)\n Do you extend the lifetime of ${INSTANCE_NAME}?\"
                  },
                  \"accessory\": {
                    \"type\": \"button\",
                    \"text\": {
                      \"type\": \"plain_text\",
                      \"text\": \"Extend\",
                      \"emoji\": true
                    },
                    \"value\": \"${INSTANCE_NAME}\"
                  }
                }
              ]
            }" $SLACK_WEBHOOK_URL
          when: on_fail

jobs:
  build:
    docker:
    - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    steps:
    - checkout
    - run:
        name: Run tests
        command: |
          cd v2
          make setup
          make test
          make check-generate

workflows:
  version: 2
  main:
    jobs:
      - build
