apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  ipFamily: dual
  podSubnet: "fd00:10:244::/56,10.244.0.0/16"
  serviceSubnet: "fd00:10:96::/112,10.96.0.0/16"
  disableDefaultCNI: true
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
