apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-ipam-webhook-configuration
  annotations:
    cke.cybozu.com/inject-cacert: "true"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-ipam-webhook-configuration
  annotations:
    cke.cybozu.com/inject-cacert: "true"
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-egress-webhook-configuration
  annotations:
    cke.cybozu.com/inject-cacert: "true"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-egress-webhook-configuration
  annotations:
    cke.cybozu.com/inject-cacert: "true"
---
