name: CI
on:
  pull_request:
  push:
    branches:
      - 'master'
defaults:
  run:
    working-directory: v2
jobs:
  test:
    name: Test pkg/nodenet
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - run: make test-nodenet
        timeout-minutes: 10
